### ISSUE TITLE
作者您好，为何用code/train.py 训练后生成的是.pk文件而不是.pth文件，然后使用eval.py运行的时候在加载网络的时候报错

### ISSUE THREAD

**Issue by xuexisuanfa** [cecret3350/DEA-Net#14]
作者您好，为何用code/train.py 训练后生成的是.pk文件而不是.pth文件，然后使用eval.py运行的时候在加载网络的时候报错

**Comment by cecret3350** [comment]
> 作者您好，为何用code/train.py 训练后生成的是.pk文件而不是.pth文件，然后使用eval.py运行的时候在加载网络的时候报错
您好，关于pk和pth后缀，可以在保存权重或者读取权重的时候更改一下后缀即可。
使用eval.py加载train.py训练后的模型报错，是因为train.py训练后的模型还没有经过重参数化。可以修改eval.py，将定义的网络修改成训练时的网络。

**Comment by Baekstar** [comment]
> 作者您好，为何用code/train.py 训练后生成的是.pk文件而不是.pth文件，然后使用eval.py运行的时候在加载网络的时候报错

您好，请问您是怎么解决的啊？

**Comment by Dyf-hue** [comment]
> 作者您好，为何用code/train.py 训练后生成的是.pk文件而不是.pth文件，然后使用eval.py运行的时候在加载网络的时候报错

您好！请问您解决了吗，我也遇到了同样的问题，希望您看到后能回复一下，非常感谢1
