### ISSUE TITLE
模型验证问题

### ISSUE THREAD

**Issue by Lxh1992** [cecret3350/DEA-Net#15]
作者，您好！
我在使用预训练的“PSNR4131_SSIM9945.pth”在ITS数据集上进行验证时发现以下问题，因为在SOTS-Indoor数据集中清晰图像会有一圈白边，导致图像尺寸为(1,3,480,640)，如果不去白边，运行eval.py会出现以下问题
`evaluation:   0%|                                                                                                                                                             | 0/500 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "eval.py", line 59, in <module>
    avg_psnr, avg_ssim = eval(val_loader, network)
  File "eval.py", line 35, in eval
    psnr_tmp = val_psnr(output, clear_img)
  File "E:\Mycode\DEA-Net\code\utils\metric.py", line 53, in val_psnr
    imdff = pred - gt
ValueError: operands could not be broadcast together with shapes (1,3,460,620) (1,3,480,640)`
但是如果把白边去除，让清晰图像的尺寸为 (1,3,460,620)时，验证结果如下：
`evaluation: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:29<00:00, 16.89it/s]
Evaluation on ITS
PSNR:25.27524749248922
SSIM:0.8369731739759445`
远低于41.31和0.9945
几种图像如下所示
不知道是哪边设置有问题，希望作者能帮忙指点一下，十分感谢！
相关图像如下图所示：
原始清晰图像
![1400_Ori](https://github.com/cecret3350/DEA-Net/assets/15494256/60ba899f-c382-48a8-a224-f4f84480ee0f)
去除白边后的图像
![1400](https://github.com/cecret3350/DEA-Net/assets/15494256/838730b7-4f93-47ae-93b0-73125971962e)
有雾图像
![1400_1](https://github.com/cecret3350/DEA-Net/assets/15494256/067b20cd-e7eb-4389-b2f2-ac448e275c5b)

**Comment by weiMytian** [comment]
> 作者，您好！ 我在使用预训练的“PSNR4131_SSIM9945.pth”在ITS数据集上进行验证时发现以下问题，因为在SOTS-Indoor数据集中清晰图像会有一圈白边，导致图像尺寸为(1,3,480,640)，如果不去白边，运行eval.py会出现以下问题 `evaluation: 0%| | 0/500 [00:01<?, ?it/s] Traceback (most recent call last): File "eval.py", line 59, in <module> avg_psnr, avg_ssim = eval(val_loader, network) File "eval.py", line 35, in eval psnr_tmp = val_psnr(output, clear_img) File "E:\Mycode\DEA-Net\code\utils\metric.py", line 53, in val_psnr imdff = pred - gt ValueError: operands could not be broadcast together with shapes (1,3,460,620) (1,3,480,640)` 但是如果把白边去除，让清晰图像的尺寸为 (1,3,460,620)时，验证结果如下： `evaluation: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:29<00:00, 16.89it/s] Evaluation on ITS PSNR:25.27524749248922 SSIM:0.8369731739759445` 远低于41.31和0.9945 几种图像如下所示 不知道是哪边设置有问题，希望作者能帮忙指点一下，十分感谢！ 相关图像如下图所示： 原始清晰图像 ![1400_Ori](https://private-user-images.githubusercontent.com/15494256/306893358-60ba899f-c382-48a8-a224-f4f84480ee0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDc5MDIsIm5iZiI6MTcwOTQ0NzYwMiwicGF0aCI6Ii8xNTQ5NDI1Ni8zMDY4OTMzNTgtNjBiYTg5OWYtYzM4Mi00OGE4LWEyMjQtZjRmODQ0ODBlZTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA2MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTE2MmQ2ZmFlZTE4Y2ViNjBhMGIwNTFlNmZkZmE5NDhjNzQzZDQ3MWQ0ZjYyNTI2OGNhNjcyNDk4ZDE1NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqUA98GmL0pvGoHW69MMAvbPLb3KL2P_vAzuZ67FVeY) 去除白边后的图像 ![1400](https://private-user-images.githubusercontent.com/15494256/306893347-838730b7-4f93-47ae-93b0-73125971962e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDc5MDIsIm5iZiI6MTcwOTQ0NzYwMiwicGF0aCI6Ii8xNTQ5NDI1Ni8zMDY4OTMzNDctODM4NzMwYjctNGY5My00N2FlLTkzYjAtNzMxMjU5NzE5NjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA2MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNWUxYjVkNDE5MDhmMzBkOTc3NGMwMjQwNmIzZWNhMTc3M2YyMDk4Mzk3YzExMjVmNTQxZGNjZTU3NTkzYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.55IDSudOjWatN75-YIiTKRDCq5o3CqTNF7kJTlruLoI) 有雾图像 ![1400_1](https://private-user-images.githubusercontent.com/15494256/306893672-067b20cd-e7eb-4389-b2f2-ac448e275c5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDc5MDIsIm5iZiI6MTcwOTQ0NzYwMiwicGF0aCI6Ii8xNTQ5NDI1Ni8zMDY4OTM2NzItMDY3YjIwY2QtZTdlYi00Mzg5LWIyZjItYWM0NDhlMjc1YzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA2MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MTc5ZDM2YzdjMTMxY2E5OTQ3ZDcxNjMxNzVhNGFkNjA2ZWU1MzdkMGY3ODQxZTk3MWE0MjhhMzM0Zjc3MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GquasrkTg0imyb8Zk4nZ82mT9D0vY_BLWLOvgK3byLc)

你好，我不是作者哈，我做的实验去掉白边后验证的结果和作者论文给的结果是一致的，你可以看一下自己裁剪方式是否有问题。我复现的问题是这个权重去验证ITS数据集的val数据集的时候差距较大。

**Comment by ChengchengFU** [comment]
> > 作者，您好！ 我在使用预训练的“PSNR4131_SSIM9945.pth”在ITS数据集上进行验证时发现以下问题，因为在SOTS-Indoor数据集中清晰图像会有一圈白边，导致图像尺寸为（1,3,480,640），如果不去白边，运行 eval.py 会出现以下问题 但是如果把白边去除，让清晰图像的尺寸为 （1,3,460,620）时，验证结果如下： 远低于41.31和0.9945 几种图像如下所示 不知道是哪边设置有问题，希望作者能帮忙指点一下，十分感谢！ 相关图像如下图所示： 原始清晰图像 ![1400_Ori](https://private-user-images.githubusercontent.com/15494256/306893358-60ba899f-c382-48a8-a224-f4f84480ee0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDc5MDIsIm5iZiI6MTcwOTQ0NzYwMiwicGF0aCI6Ii8xNTQ5NDI1Ni8zMDY4OTMzNTgtNjBiYTg5OWYtYzM4Mi00OGE4LWEyMjQtZjRmODQ0ODBlZTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA2MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTE2MmQ2ZmFlZTE4Y2ViNjBhMGIwNTFlNmZkZmE5NDhjNzQzZDQ3MWQ0ZjYyNTI2OGNhNjcyNDk4ZDE1NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqUA98GmL0pvGoHW69MMAvbPLb3KL2P_vAzuZ67FVeY) 去除白边后的图像 ![1400](https://private-user-images.githubusercontent.com/15494256/306893347-838730b7-4f93-47ae-93b0-73125971962e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDc5MDIsIm5iZiI6MTcwOTQ0NzYwMiwicGF0aCI6Ii8xNTQ5NDI1Ni8zMDY4OTMzNDctODM4NzMwYjctNGY5My00N2FlLTkzYjAtNzMxMjU5NzE5NjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA2MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNWUxYjVkNDE5MDhmMzBkOTc3NGMwMjQwNmIzZWNhMTc3M2YyMDk4Mzk3YzExMjVmNTQxZGNjZTU3NTkzYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.55IDSudOjWatN75-YIiTKRDCq5o3CqTNF7kJTlruLoI) 有雾图像`evaluation: 0%| | 0/500 [00:01<?, ?it/s] Traceback (most recent call last): File "eval.py", line 59, in <module> avg_psnr, avg_ssim = eval(val_loader, network) File "eval.py", line 35, in eval psnr_tmp = val_psnr(output, clear_img) File "E:\Mycode\DEA-Net\code\utils\metric.py", line 53, in val_psnr imdff = pred - gt ValueError: operands could not be broadcast together with shapes (1,3,460,620) (1,3,480,640)``evaluation: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:29<00:00, 16.89it/s] Evaluation on ITS PSNR:25.27524749248922 SSIM:0.8369731739759445`![1400_1](https://private-user-images.githubusercontent.com/15494256/306893672-067b20cd-e7eb-4389-b2f2-ac448e275c5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDc5MDIsIm5iZiI6MTcwOTQ0NzYwMiwicGF0aCI6Ii8xNTQ5NDI1Ni8zMDY4OTM2NzItMDY3YjIwY2QtZTdlYi00Mzg5LWIyZjItYWM0NDhlMjc1YzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA2MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MTc5ZDM2YzdjMTMxY2E5OTQ3ZDcxNjMxNzVhNGFkNjA2ZWU1MzdkMGY3ODQxZTk3MWE0MjhhMzM0Zjc3MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GquasrkTg0imyb8Zk4nZ82mT9D0vY_BLWLOvgK3byLc)
> 
> 你好，我不是作者哈，我做的实验去掉白边后验证的结果和作者论文给的结果是一致的，你可以看一下自己裁剪方式是否有问题。我复现的问题是这个权重去验证ITS数据集的val数据集的时候差距较大。

你好，我在验证过程中也遇到了同样的问题，请问你是如何裁剪图片的呢，能否指点一二，我的邮箱是1603995227@qq.com，盼回复，十分感谢！

**Comment by ChengchengFU** [comment]
clear图像中心裁剪后再使用（(480,640)-->(460,620)），验证无问题

from PIL import Image
import os

input_folder = "./clear"
output_folder = "./croped"

# 创建输出文件夹
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

for i in range(1400, 1450):
    filename = f"{i}.png"
    input_path = os.path.join(input_folder, filename)
    output_path = os.path.join(output_folder, filename)

    if os.path.exists(input_path):
        # 打开原始图片
        image = Image.open(input_path)

        # 获取原始图片的宽度和高度
        width, height = image.size

        # 计算裁剪的起始坐标
        left = (width - 620) // 2
        top = (height - 460) // 2
        right = left + 620
        bottom = top + 460

        # 裁剪图片
        cropped_image = image.crop((left, top, right, bottom))

        # 保存裁剪后的图片
        cropped_image.save(output_path)

        print(f"Cropped image {filename}")
    else:
        print(f"Image {filename} not found")

**Comment by ChengchengFU** [comment]
clear图像中心裁剪后再使用（(480,640)-->(460,620)），验证无问题


from PIL import Image
import os

input_folder = "./clear"
output_folder = "./croped"

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

for i in range(1400, 1450):
    filename = f"{i}.png"
    input_path = os.path.join(input_folder, filename)
    output_path = os.path.join(output_folder, filename)

    if os.path.exists(input_path):
        # 打开原始图片
        image = Image.open(input_path)

        # 获取原始图片的宽度和高度
        width, height = image.size

        # 计算裁剪的起始坐标
        left = (width - 620) // 2
        top = (height - 460) // 2
        right = left + 620
        bottom = top + 460

        # 裁剪图片
        cropped_image = image.crop((left, top, right, bottom))

        # 保存裁剪后的图片
        cropped_image.save(output_path)

        print(f"Cropped image {filename}")
    else:
        print(f"Image {filename} not found")

**Comment by Lxh1992** [comment]
感谢感谢，终于解决了！
