### ISSUE TITLE
Backbone和Backbone_train有什么区别，为什么单独分开

### ISSUE THREAD

**Issue by qqbangbangbang** [cecret3350/DEA-Net#18]

**Comment by cecret3350** [comment]
你好，Backbone是完成训练后，经过重参数化后的模型，DEConv在这里体现为一个常规卷积。
而Backbone_train则包含了训练时的DEConv。

**Comment by tamwaiban** [comment]
你好，请问你是如何将DEConv重参数化为常规卷积的呢，没有在你代码中看到相关实现，方便说一下吗？是直接使用DEConv中最后的‘conv1_5’吗？

**Comment by cecret3350** [comment]
> 你好，请问你是如何将DEConv重参数化为常规卷积的呢，没有在你代码中看到相关实现，方便说一下吗？是直接使用DEConv中最后的‘conv1_5’吗？

你好，抱歉这么晚回复。我已经更新了重参数化的代码，请查看[code/reparam.py](https://github.com/cecret3350/DEA-Net/blob/a327b19666877467a1f21514962ce126982defc3/code/reparam.py)
