### ISSUE TITLE
A question about DEConv

### ISSUE THREAD

**Issue by hushuaiouc** [cecret3350/DEA-Net#2]
Hello I didn't see the other four conv in your code where is it?

![image](https://user-images.githubusercontent.com/58196478/217559813-b85302d1-8e70-4613-82d9-49ea5d9886d7.png)
![image](https://user-images.githubusercontent.com/58196478/217560115-f6d6f8be-a396-4462-8668-831388f7539d.png)

**Comment by cecret3350** [comment]
Hi,
At this stage, we have only released our evaluation code. And we re-parameterized four difference convolutions and a vanilla convolution to one convolution after the training is completed. Therefore reflected in evaluation code, there is only one convolution.
We will release the specific implementation of DEConv during training later.
I hope this reply will solve your problem.


> Hello I didn't see the other four conv in your code where is it?
> 
> ![image](https://user-images.githubusercontent.com/58196478/217559813-b85302d1-8e70-4613-82d9-49ea5d9886d7.png) ![image](https://user-images.githubusercontent.com/58196478/217560115-f6d6f8be-a396-4462-8668-831388f7539d.png)
