### ISSUE TITLE
怎么把自己训练出来的模型用来评估

### ISSUE THREAD

**Issue by ZHB2333** [cecret3350/DEA-Net#22]
大神您好，想问一下，训练之后保存的模型是.pk文件，但是评估模型是.pth文件，怎么才能把自己训练出来的模型用来评估呢

**Comment by wengzp1** [comment]
> 大神您好，想问一下，训练之后保存的模型是.pk文件，但是评估模型是.pth文件，怎么才能把自己训练出来的模型用来评估呢

您好，请问您解决这个问题了吗

**Comment by ZHB2333** [comment]
> > 大神您好，想问一下，训练之后保存的模型是.pk文件，但是评估模型是.pth文件，怎么才能把自己训练出来的模型用来评估呢
> 
> 您好，请问您解决这个问题了吗

解决了，在.pk中需要读取state_dict中的model字段，其次读取后可能还需要将多出来的weight后缀去掉

**Comment by wengzp1** [comment]
> > > 大神您好，想问一下，训练之后保存的模型是.pk文件，但是评估模型是.pth文件，怎么才能把自己训练出来的模型用来评估呢
> > 
> > 
> > 您好，请问您解决这个问题了吗
> 
> 解决了，在.pk中需要读取state_dict中的model字段，其次读取后可能还需要将多出来的weight后缀去掉

你好，请问有eval.py修改后的文件吗，我想看一下
