### ISSUE TITLE
DEBlock

### ISSUE THREAD

**Issue by shangyuu** [cecret3350/DEA-Net#3]
您好
我拜读了您关于单图像去雾的论文-DEA-Net: Single image dehazing based on detail-enhanced convolution and content-guided attention
是个令人印象深刻且佩服的研究
在论文中有提到它整合了4个差分卷积以及一个普通卷积 但我在程式码裡头只有看到一个普通卷积
请问是尚未上传完全吗? 还是只是因为我没有仔细看清楚呢?

**Comment by cecret3350** [comment]
您好，感谢您对我们工作的认可。
在训练完成后，我们将DEConv中的四个差分卷积和一个普通卷积重参数化为一个卷积。
我们目前上传的代码和模型都是经过重参数化后的最终模型，因此体现在代码中只有一个普通卷积。
我们将在将来发布未经过重参数化的代码，欢迎对我们的工作继续保持关注。
