### ISSUE TITLE
About the training code

### ISSUE THREAD

**Issue by kkllww** [cecret3350/DEA-Net#5]
Please ask when will you release the training code, or if it is convenient, can you give me a copy of the code, my email address is 1715005876@qq.com, thank you very much for your help, your results are only used to help my academic research, there will be no other use, I look forward to your reply.

**Comment by hezw2016** [comment]
Hi kkllww,

We just submitted our paper to an IEEE journal. At this point, we have no plan to release our training code directly.
But, we will make it public which is for sure. I guess maybe after receiving the first round result of the review.
Thank you very much for paying attention to our work.

Best,
Zewei

**Comment by tangjingwe** [comment]
I am also looking forward to your publication of your training code, which will be of great help to my studies and research.my email address is 1220378814@qq.com.

**Comment by cecret3350** [comment]
Hi, we have released implementation of DEConv and training codes, enjoy :D.
