### ISSUE TITLE
DEConv

### ISSUE THREAD

**Issue by liux520** [cecret3350/DEA-Net#7]
The DEConv of Figure 3 is implemented in the code only through a normal 3x3 convolution?

**Comment by cecret3350** [comment]
Hi,

The reason for this phenomenon is that our DEConv is implemented differently during training and inference.

During training, our DEConv consists of 1 Vanilla Conv and 4 Difference Conv. After training, we merge these 5 convolutions into 1 convolution by reparameterization, so only 1 convolution of 3x3 is needed to implement it. 

The code and weights we have published so far correspond to the reparameterized model, so DEConv is represented in the code as a 3x3 convolution.

I hope my reply can solve your problem.
